import { Tabs } from "@heroui/tabs";
import { extendVariants } from "@heroui/system";

export const ClassicTabs = extendVariants(Tabs, {
    variants: {
        variant: {
            cso: {
                base: "w-full",
                tabList: [
                    "rounded-none",
                    "first:rounded-tl-[12px]",
                    "last:rounded-tr-[12px]",
                    "!outline-hidden",
                    "!outline-width-0",
                    "gap-0",
                    "w-full",
                    "relative",
                    "rounded-t-lg",
                    "overflow-hidden",
                    "p-0",
                    "opacity-100",
                    "data-[selected=false]:bg-grey-dark",
                    "shadow-none",
                ],
                tab: [
                    "flex-1",
                    "py-3",
                    "px-4",
                    "font-bold",
                    "text-white",
                    "bg-orange",
                    "transition-all",
                    "duration-200",
                    "data-[selected=true]:bg-grey-dark",
                    "data-[selected=true]:text-white",
                    "data-[selected=true]:cursor-default",
                    "data-[selected=true]:pointer-events-none",
                    "data-[selected=true]:!outline-hidden",
                    "data-[focus-visible=true]:outline-none",
                    "border-none",
                    "rounded-none",
                    "first:rounded-tl-[12px]",
                    "last:rounded-tr-[12px]",
                    "h-auto",
                    "uppercase",
                    "tracking-wide",
                    "!outline-hidden",
                    "!outline-width-0",
                    // Style avec ombre comme StyledButton
                    "data-[selected=false]:shadow-[0_6px_0_0_rgba(0,0,0,0.3)]",
                    "data-[selected=false]:hover:translate-y-[6px]",
                    "data-[selected=false]:hover:shadow-[0_0px_0_0_rgba(0,0,0,0.3)]",
                    "data-[selected=false]:transition-transform",
                    "data-[selected=false]:duration-150",
                    "data-[selected=false]:ease-in-out",
                ],
                tabContent: [
                    "group-data-[selected=true]:text-white",
                    "text-white",
                    "font-bold",
                    "!outline-hidden",
                    "!outline-width-0",
                ],
                cursor: ["hidden"],
                panel: [
                    "p-6",
                    "bg-grey-dark",
                    "rounded-b-lg",
                    "!outline-hidden",
                    "!outline-width-0",
                ],
            },
            clean: {
                base: "w-full",
                tabList: ["gap-2", "w-full", "bg-transparent", "p-1"],
                tab: [
                    "rounded-none",
                    "first:rounded-tl-[10px]",
                    "last:rounded-tr-[10px]",
                    "px-4",
                    "py-2",
                    "font-medium",
                    "text-gray-600",
                    "data-[selected=true]:text-orange",
                    "data-[selected=true]:bg-white",
                    "data-[selected=true]:shadow-md",
                    "hover:text-gray-800",
                    "transition-all",
                ],
                panel: "p-4",
            },
        },
    },
    defaultVariants: {
        variant: "cso",
    },
});
